spring:
  data:
    mongodb:
      uri: mongodb+srv://archery:dARcTJYHRXfBEPHi@cluster0.bnnzxz6.mongodb.net/?retryWrites=true&w=majority
      database: archery
      uuid-representation: standard
  security:
    user:
      password: password
      name: name

api:
  path: /api/archery

archery:
  jwtSecret: archerySecretAu5nUNazDknDpRObLjYtmrRhX6hMTXAEb4U64BP7qiboL5LI28kpqRjBh8Sa
  jwtExpirationMs: 86400000
