spring:
  datasource:
    url: jdbc:h2:file:./data/archerydb
    username: archery
    password: archery
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  security:
    user:
      password: password
      name: name

api:
  path: /api/archery